name: Go

on: 
  push: 
    branches: [ main, staging, develop ]
  pull_request: 
    branches: [ main, staging, develop ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Install dependencies
      run: |
        go version
        go get -u golang.org/x/lint/golint
  
    - name: Build
      run: go build .

    - name: Run vet & lint
      run: |
        go vet .
        golint .

    - name: Send slack notification
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      if: always()

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    if: ${{ github.ref == ‘refs/heads/master’ && github.event_name == ‘push’ }} 
    steps:
    - uses: actions/checkout@v2
    - name: Deploy to Docker registry
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: sorooshansari/go-api
        tag_with_ref: true